// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/hypothesis.proto

package hypothesis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HypothesisRegistry_SubmitHypotheses_FullMethodName = "/runtime.hypothesis.HypothesisRegistry/SubmitHypotheses"
	HypothesisRegistry_GetHypotheses_FullMethodName    = "/runtime.hypothesis.HypothesisRegistry/GetHypotheses"
)

// HypothesisRegistryClient is the client API for HypothesisRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HypothesisRegistryClient interface {
	SubmitHypotheses(ctx context.Context, in *HypothesisReport, opts ...grpc.CallOption) (*RegistryResponse, error)
	GetHypotheses(ctx context.Context, in *SessionQuery, opts ...grpc.CallOption) (*HypothesisReport, error)
}

type hypothesisRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewHypothesisRegistryClient(cc grpc.ClientConnInterface) HypothesisRegistryClient {
	return &hypothesisRegistryClient{cc}
}

func (c *hypothesisRegistryClient) SubmitHypotheses(ctx context.Context, in *HypothesisReport, opts ...grpc.CallOption) (*RegistryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryResponse)
	err := c.cc.Invoke(ctx, HypothesisRegistry_SubmitHypotheses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypothesisRegistryClient) GetHypotheses(ctx context.Context, in *SessionQuery, opts ...grpc.CallOption) (*HypothesisReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HypothesisReport)
	err := c.cc.Invoke(ctx, HypothesisRegistry_GetHypotheses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HypothesisRegistryServer is the server API for HypothesisRegistry service.
// All implementations must embed UnimplementedHypothesisRegistryServer
// for forward compatibility.
type HypothesisRegistryServer interface {
	SubmitHypotheses(context.Context, *HypothesisReport) (*RegistryResponse, error)
	GetHypotheses(context.Context, *SessionQuery) (*HypothesisReport, error)
	mustEmbedUnimplementedHypothesisRegistryServer()
}

// UnimplementedHypothesisRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHypothesisRegistryServer struct{}

func (UnimplementedHypothesisRegistryServer) SubmitHypotheses(context.Context, *HypothesisReport) (*RegistryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitHypotheses not implemented")
}
func (UnimplementedHypothesisRegistryServer) GetHypotheses(context.Context, *SessionQuery) (*HypothesisReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHypotheses not implemented")
}
func (UnimplementedHypothesisRegistryServer) mustEmbedUnimplementedHypothesisRegistryServer() {}
func (UnimplementedHypothesisRegistryServer) testEmbeddedByValue()                            {}

// UnsafeHypothesisRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypothesisRegistryServer will
// result in compilation errors.
type UnsafeHypothesisRegistryServer interface {
	mustEmbedUnimplementedHypothesisRegistryServer()
}

func RegisterHypothesisRegistryServer(s grpc.ServiceRegistrar, srv HypothesisRegistryServer) {
	// If the following call panics, it indicates UnimplementedHypothesisRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HypothesisRegistry_ServiceDesc, srv)
}

func _HypothesisRegistry_SubmitHypotheses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HypothesisReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypothesisRegistryServer).SubmitHypotheses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HypothesisRegistry_SubmitHypotheses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypothesisRegistryServer).SubmitHypotheses(ctx, req.(*HypothesisReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _HypothesisRegistry_GetHypotheses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypothesisRegistryServer).GetHypotheses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HypothesisRegistry_GetHypotheses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypothesisRegistryServer).GetHypotheses(ctx, req.(*SessionQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// HypothesisRegistry_ServiceDesc is the grpc.ServiceDesc for HypothesisRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HypothesisRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.hypothesis.HypothesisRegistry",
	HandlerType: (*HypothesisRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitHypotheses",
			Handler:    _HypothesisRegistry_SubmitHypotheses_Handler,
		},
		{
			MethodName: "GetHypotheses",
			Handler:    _HypothesisRegistry_GetHypotheses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hypothesis.proto",
}
