// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/hypothesis.proto

package hypothesis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MechanismClass int32

const (
	MechanismClass_UNKNOWN_MECHANISM      MechanismClass = 0
	MechanismClass_PARSER_DIFFERENTIAL    MechanismClass = 1
	MechanismClass_IDENTITY_LEAK          MechanismClass = 2
	MechanismClass_WORKLOAD_ESCALATION    MechanismClass = 3
	MechanismClass_ASYNC_TRUST_DECAY      MechanismClass = 4
	MechanismClass_CONSISTENCY_FAILURE    MechanismClass = 5
	MechanismClass_STALE_AUTH_PROPAGATION MechanismClass = 6
)

// Enum value maps for MechanismClass.
var (
	MechanismClass_name = map[int32]string{
		0: "UNKNOWN_MECHANISM",
		1: "PARSER_DIFFERENTIAL",
		2: "IDENTITY_LEAK",
		3: "WORKLOAD_ESCALATION",
		4: "ASYNC_TRUST_DECAY",
		5: "CONSISTENCY_FAILURE",
		6: "STALE_AUTH_PROPAGATION",
	}
	MechanismClass_value = map[string]int32{
		"UNKNOWN_MECHANISM":      0,
		"PARSER_DIFFERENTIAL":    1,
		"IDENTITY_LEAK":          2,
		"WORKLOAD_ESCALATION":    3,
		"ASYNC_TRUST_DECAY":      4,
		"CONSISTENCY_FAILURE":    5,
		"STALE_AUTH_PROPAGATION": 6,
	}
)

func (x MechanismClass) Enum() *MechanismClass {
	p := new(MechanismClass)
	*p = x
	return p
}

func (x MechanismClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MechanismClass) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_hypothesis_proto_enumTypes[0].Descriptor()
}

func (MechanismClass) Type() protoreflect.EnumType {
	return &file_proto_hypothesis_proto_enumTypes[0]
}

func (x MechanismClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MechanismClass.Descriptor instead.
func (MechanismClass) EnumDescriptor() ([]byte, []int) {
	return file_proto_hypothesis_proto_rawDescGZIP(), []int{0}
}

type AttackHypothesis struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mechanism               MechanismClass         `protobuf:"varint,2,opt,name=mechanism,proto3,enum=runtime.hypothesis.MechanismClass" json:"mechanism,omitempty"`
	PathNodeIds             []string               `protobuf:"bytes,3,rep,name=path_node_ids,json=pathNodeIds,proto3" json:"path_node_ids,omitempty"`
	RiskScore               float32                `protobuf:"fixed32,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	ConfidenceScore         float32                `protobuf:"fixed32,5,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	EvidenceIds             []string               `protobuf:"bytes,6,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	Rationale               string                 `protobuf:"bytes,7,opt,name=rationale,proto3" json:"rationale,omitempty"`
	ExplainabilityTraceId   string                 `protobuf:"bytes,8,opt,name=explainability_trace_id,json=explainabilityTraceId,proto3" json:"explainability_trace_id,omitempty"`
	ArchitecturalIndicators map[string]string      `protobuf:"bytes,9,rep,name=architectural_indicators,json=architecturalIndicators,proto3" json:"architectural_indicators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., "cloud": "aws"
	GeneratedAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	PriorityRanking         int32                  `protobuf:"varint,11,opt,name=priority_ranking,json=priorityRanking,proto3" json:"priority_ranking,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AttackHypothesis) Reset() {
	*x = AttackHypothesis{}
	mi := &file_proto_hypothesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackHypothesis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackHypothesis) ProtoMessage() {}

func (x *AttackHypothesis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypothesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackHypothesis.ProtoReflect.Descriptor instead.
func (*AttackHypothesis) Descriptor() ([]byte, []int) {
	return file_proto_hypothesis_proto_rawDescGZIP(), []int{0}
}

func (x *AttackHypothesis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AttackHypothesis) GetMechanism() MechanismClass {
	if x != nil {
		return x.Mechanism
	}
	return MechanismClass_UNKNOWN_MECHANISM
}

func (x *AttackHypothesis) GetPathNodeIds() []string {
	if x != nil {
		return x.PathNodeIds
	}
	return nil
}

func (x *AttackHypothesis) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AttackHypothesis) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *AttackHypothesis) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

func (x *AttackHypothesis) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *AttackHypothesis) GetExplainabilityTraceId() string {
	if x != nil {
		return x.ExplainabilityTraceId
	}
	return ""
}

func (x *AttackHypothesis) GetArchitecturalIndicators() map[string]string {
	if x != nil {
		return x.ArchitecturalIndicators
	}
	return nil
}

func (x *AttackHypothesis) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *AttackHypothesis) GetPriorityRanking() int32 {
	if x != nil {
		return x.PriorityRanking
	}
	return 0
}

type HypothesisReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Hypotheses    []*AttackHypothesis    `protobuf:"bytes,2,rep,name=hypotheses,proto3" json:"hypotheses,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HypothesisReport) Reset() {
	*x = HypothesisReport{}
	mi := &file_proto_hypothesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HypothesisReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypothesisReport) ProtoMessage() {}

func (x *HypothesisReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypothesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypothesisReport.ProtoReflect.Descriptor instead.
func (*HypothesisReport) Descriptor() ([]byte, []int) {
	return file_proto_hypothesis_proto_rawDescGZIP(), []int{1}
}

func (x *HypothesisReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HypothesisReport) GetHypotheses() []*AttackHypothesis {
	if x != nil {
		return x.Hypotheses
	}
	return nil
}

func (x *HypothesisReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RegistryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RegisteredIds []string               `protobuf:"bytes,2,rep,name=registered_ids,json=registeredIds,proto3" json:"registered_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryResponse) Reset() {
	*x = RegistryResponse{}
	mi := &file_proto_hypothesis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryResponse) ProtoMessage() {}

func (x *RegistryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypothesis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryResponse.ProtoReflect.Descriptor instead.
func (*RegistryResponse) Descriptor() ([]byte, []int) {
	return file_proto_hypothesis_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistryResponse) GetRegisteredIds() []string {
	if x != nil {
		return x.RegisteredIds
	}
	return nil
}

type SessionQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MinRisk       float32                `protobuf:"fixed32,2,opt,name=min_risk,json=minRisk,proto3" json:"min_risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionQuery) Reset() {
	*x = SessionQuery{}
	mi := &file_proto_hypothesis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionQuery) ProtoMessage() {}

func (x *SessionQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hypothesis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionQuery.ProtoReflect.Descriptor instead.
func (*SessionQuery) Descriptor() ([]byte, []int) {
	return file_proto_hypothesis_proto_rawDescGZIP(), []int{3}
}

func (x *SessionQuery) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionQuery) GetMinRisk() float32 {
	if x != nil {
		return x.MinRisk
	}
	return 0
}

var File_proto_hypothesis_proto protoreflect.FileDescriptor

const file_proto_hypothesis_proto_rawDesc = "" +
	"\n" +
	"\x16proto/hypothesis.proto\x12\x12runtime.hypothesis\x1a\x1fgoogle/protobuf/timestamp.proto\"\xff\x04\n" +
	"\x10AttackHypothesis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12@\n" +
	"\tmechanism\x18\x02 \x01(\x0e2\".runtime.hypothesis.MechanismClassR\tmechanism\x12\"\n" +
	"\rpath_node_ids\x18\x03 \x03(\tR\vpathNodeIds\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x02R\triskScore\x12)\n" +
	"\x10confidence_score\x18\x05 \x01(\x02R\x0fconfidenceScore\x12!\n" +
	"\fevidence_ids\x18\x06 \x03(\tR\vevidenceIds\x12\x1c\n" +
	"\trationale\x18\a \x01(\tR\trationale\x126\n" +
	"\x17explainability_trace_id\x18\b \x01(\tR\x15explainabilityTraceId\x12|\n" +
	"\x18architectural_indicators\x18\t \x03(\v2A.runtime.hypothesis.AttackHypothesis.ArchitecturalIndicatorsEntryR\x17architecturalIndicators\x12=\n" +
	"\fgenerated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12)\n" +
	"\x10priority_ranking\x18\v \x01(\x05R\x0fpriorityRanking\x1aJ\n" +
	"\x1cArchitecturalIndicatorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x01\n" +
	"\x10HypothesisReport\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12D\n" +
	"\n" +
	"hypotheses\x18\x02 \x03(\v2$.runtime.hypothesis.AttackHypothesisR\n" +
	"hypotheses\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"S\n" +
	"\x10RegistryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eregistered_ids\x18\x02 \x03(\tR\rregisteredIds\"H\n" +
	"\fSessionQuery\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bmin_risk\x18\x02 \x01(\x02R\aminRisk*\xb8\x01\n" +
	"\x0eMechanismClass\x12\x15\n" +
	"\x11UNKNOWN_MECHANISM\x10\x00\x12\x17\n" +
	"\x13PARSER_DIFFERENTIAL\x10\x01\x12\x11\n" +
	"\rIDENTITY_LEAK\x10\x02\x12\x17\n" +
	"\x13WORKLOAD_ESCALATION\x10\x03\x12\x15\n" +
	"\x11ASYNC_TRUST_DECAY\x10\x04\x12\x17\n" +
	"\x13CONSISTENCY_FAILURE\x10\x05\x12\x1a\n" +
	"\x16STALE_AUTH_PROPAGATION\x10\x062\xcd\x01\n" +
	"\x12HypothesisRegistry\x12^\n" +
	"\x10SubmitHypotheses\x12$.runtime.hypothesis.HypothesisReport\x1a$.runtime.hypothesis.RegistryResponse\x12W\n" +
	"\rGetHypotheses\x12 .runtime.hypothesis.SessionQuery\x1a$.runtime.hypothesis.HypothesisReportB,Z*github.com/hacker/runtime/proto/hypothesisb\x06proto3"

var (
	file_proto_hypothesis_proto_rawDescOnce sync.Once
	file_proto_hypothesis_proto_rawDescData []byte
)

func file_proto_hypothesis_proto_rawDescGZIP() []byte {
	file_proto_hypothesis_proto_rawDescOnce.Do(func() {
		file_proto_hypothesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hypothesis_proto_rawDesc), len(file_proto_hypothesis_proto_rawDesc)))
	})
	return file_proto_hypothesis_proto_rawDescData
}

var file_proto_hypothesis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_hypothesis_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_hypothesis_proto_goTypes = []any{
	(MechanismClass)(0),           // 0: runtime.hypothesis.MechanismClass
	(*AttackHypothesis)(nil),      // 1: runtime.hypothesis.AttackHypothesis
	(*HypothesisReport)(nil),      // 2: runtime.hypothesis.HypothesisReport
	(*RegistryResponse)(nil),      // 3: runtime.hypothesis.RegistryResponse
	(*SessionQuery)(nil),          // 4: runtime.hypothesis.SessionQuery
	nil,                           // 5: runtime.hypothesis.AttackHypothesis.ArchitecturalIndicatorsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_hypothesis_proto_depIdxs = []int32{
	0, // 0: runtime.hypothesis.AttackHypothesis.mechanism:type_name -> runtime.hypothesis.MechanismClass
	5, // 1: runtime.hypothesis.AttackHypothesis.architectural_indicators:type_name -> runtime.hypothesis.AttackHypothesis.ArchitecturalIndicatorsEntry
	6, // 2: runtime.hypothesis.AttackHypothesis.generated_at:type_name -> google.protobuf.Timestamp
	1, // 3: runtime.hypothesis.HypothesisReport.hypotheses:type_name -> runtime.hypothesis.AttackHypothesis
	6, // 4: runtime.hypothesis.HypothesisReport.timestamp:type_name -> google.protobuf.Timestamp
	2, // 5: runtime.hypothesis.HypothesisRegistry.SubmitHypotheses:input_type -> runtime.hypothesis.HypothesisReport
	4, // 6: runtime.hypothesis.HypothesisRegistry.GetHypotheses:input_type -> runtime.hypothesis.SessionQuery
	3, // 7: runtime.hypothesis.HypothesisRegistry.SubmitHypotheses:output_type -> runtime.hypothesis.RegistryResponse
	2, // 8: runtime.hypothesis.HypothesisRegistry.GetHypotheses:output_type -> runtime.hypothesis.HypothesisReport
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_hypothesis_proto_init() }
func file_proto_hypothesis_proto_init() {
	if File_proto_hypothesis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hypothesis_proto_rawDesc), len(file_proto_hypothesis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hypothesis_proto_goTypes,
		DependencyIndexes: file_proto_hypothesis_proto_depIdxs,
		EnumInfos:         file_proto_hypothesis_proto_enumTypes,
		MessageInfos:      file_proto_hypothesis_proto_msgTypes,
	}.Build()
	File_proto_hypothesis_proto = out.File
	file_proto_hypothesis_proto_goTypes = nil
	file_proto_hypothesis_proto_depIdxs = nil
}
