// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/reasoning.proto

package reasoning

import (
	graph "github.com/hacker/runtime/proto/graph"
	hypothesis "github.com/hacker/runtime/proto/hypothesis"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferenceTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SubGraph      *graph.GraphSnapshot   `protobuf:"bytes,3,opt,name=sub_graph,json=subGraph,proto3" json:"sub_graph,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferenceTask) Reset() {
	*x = InferenceTask{}
	mi := &file_proto_reasoning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceTask) ProtoMessage() {}

func (x *InferenceTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reasoning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceTask.ProtoReflect.Descriptor instead.
func (*InferenceTask) Descriptor() ([]byte, []int) {
	return file_proto_reasoning_proto_rawDescGZIP(), []int{0}
}

func (x *InferenceTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InferenceTask) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InferenceTask) GetSubGraph() *graph.GraphSnapshot {
	if x != nil {
		return x.SubGraph
	}
	return nil
}

func (x *InferenceTask) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type InferenceResult struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	TaskId            string                         `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Hypotheses        []*hypothesis.AttackHypothesis `protobuf:"bytes,2,rep,name=hypotheses,proto3" json:"hypotheses,omitempty"`
	ConfidenceUpdates []*ConfidenceRefinement        `protobuf:"bytes,3,rep,name=confidence_updates,json=confidenceUpdates,proto3" json:"confidence_updates,omitempty"`
	ReasoningTrace    string                         `protobuf:"bytes,4,opt,name=reasoning_trace,json=reasoningTrace,proto3" json:"reasoning_trace,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InferenceResult) Reset() {
	*x = InferenceResult{}
	mi := &file_proto_reasoning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceResult) ProtoMessage() {}

func (x *InferenceResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reasoning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceResult.ProtoReflect.Descriptor instead.
func (*InferenceResult) Descriptor() ([]byte, []int) {
	return file_proto_reasoning_proto_rawDescGZIP(), []int{1}
}

func (x *InferenceResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *InferenceResult) GetHypotheses() []*hypothesis.AttackHypothesis {
	if x != nil {
		return x.Hypotheses
	}
	return nil
}

func (x *InferenceResult) GetConfidenceUpdates() []*ConfidenceRefinement {
	if x != nil {
		return x.ConfidenceUpdates
	}
	return nil
}

func (x *InferenceResult) GetReasoningTrace() string {
	if x != nil {
		return x.ReasoningTrace
	}
	return ""
}

type ConfidenceRefinement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // Node or Edge ID
	Adjustment    float32                `protobuf:"fixed32,2,opt,name=adjustment,proto3" json:"adjustment,omitempty"`
	Rationale     string                 `protobuf:"bytes,3,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfidenceRefinement) Reset() {
	*x = ConfidenceRefinement{}
	mi := &file_proto_reasoning_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceRefinement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceRefinement) ProtoMessage() {}

func (x *ConfidenceRefinement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reasoning_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceRefinement.ProtoReflect.Descriptor instead.
func (*ConfidenceRefinement) Descriptor() ([]byte, []int) {
	return file_proto_reasoning_proto_rawDescGZIP(), []int{2}
}

func (x *ConfidenceRefinement) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ConfidenceRefinement) GetAdjustment() float32 {
	if x != nil {
		return x.Adjustment
	}
	return 0
}

func (x *ConfidenceRefinement) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type ConfidenceRefinementRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EntityId           string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	RelatedEvidenceIds []string               `protobuf:"bytes,2,rep,name=related_evidence_ids,json=relatedEvidenceIds,proto3" json:"related_evidence_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConfidenceRefinementRequest) Reset() {
	*x = ConfidenceRefinementRequest{}
	mi := &file_proto_reasoning_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidenceRefinementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidenceRefinementRequest) ProtoMessage() {}

func (x *ConfidenceRefinementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reasoning_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidenceRefinementRequest.ProtoReflect.Descriptor instead.
func (*ConfidenceRefinementRequest) Descriptor() ([]byte, []int) {
	return file_proto_reasoning_proto_rawDescGZIP(), []int{3}
}

func (x *ConfidenceRefinementRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ConfidenceRefinementRequest) GetRelatedEvidenceIds() []string {
	if x != nil {
		return x.RelatedEvidenceIds
	}
	return nil
}

var File_proto_reasoning_proto protoreflect.FileDescriptor

const file_proto_reasoning_proto_rawDesc = "" +
	"\n" +
	"\x15proto/reasoning.proto\x12\x11runtime.reasoning\x1a\x11proto/graph.proto\x1a\x16proto/hypothesis.proto\"\x93\x02\n" +
	"\rInferenceTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x129\n" +
	"\tsub_graph\x18\x03 \x01(\v2\x1c.runtime.graph.GraphSnapshotR\bsubGraph\x12P\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v20.runtime.reasoning.InferenceTask.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf1\x01\n" +
	"\x0fInferenceResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12D\n" +
	"\n" +
	"hypotheses\x18\x02 \x03(\v2$.runtime.hypothesis.AttackHypothesisR\n" +
	"hypotheses\x12V\n" +
	"\x12confidence_updates\x18\x03 \x03(\v2'.runtime.reasoning.ConfidenceRefinementR\x11confidenceUpdates\x12'\n" +
	"\x0freasoning_trace\x18\x04 \x01(\tR\x0ereasoningTrace\"q\n" +
	"\x14ConfidenceRefinement\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1e\n" +
	"\n" +
	"adjustment\x18\x02 \x01(\x02R\n" +
	"adjustment\x12\x1c\n" +
	"\trationale\x18\x03 \x01(\tR\trationale\"l\n" +
	"\x1bConfidenceRefinementRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x120\n" +
	"\x14related_evidence_ids\x18\x02 \x03(\tR\x12relatedEvidenceIds2\xb5\x01\n" +
	"\x0fReasoningWorker\x12M\n" +
	"\x05Infer\x12 .runtime.reasoning.InferenceTask\x1a\".runtime.reasoning.InferenceResult\x12S\n" +
	"\x0fAnalyzeTopology\x12\x1c.runtime.graph.GraphSnapshot\x1a\".runtime.reasoning.InferenceResult2p\n" +
	"\x10ConfidenceEngine\x12\\\n" +
	"\x06Refine\x12..runtime.reasoning.ConfidenceRefinementRequest\x1a\".runtime.reasoning.InferenceResultB+Z)github.com/hacker/runtime/proto/reasoningb\x06proto3"

var (
	file_proto_reasoning_proto_rawDescOnce sync.Once
	file_proto_reasoning_proto_rawDescData []byte
)

func file_proto_reasoning_proto_rawDescGZIP() []byte {
	file_proto_reasoning_proto_rawDescOnce.Do(func() {
		file_proto_reasoning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reasoning_proto_rawDesc), len(file_proto_reasoning_proto_rawDesc)))
	})
	return file_proto_reasoning_proto_rawDescData
}

var file_proto_reasoning_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_reasoning_proto_goTypes = []any{
	(*InferenceTask)(nil),               // 0: runtime.reasoning.InferenceTask
	(*InferenceResult)(nil),             // 1: runtime.reasoning.InferenceResult
	(*ConfidenceRefinement)(nil),        // 2: runtime.reasoning.ConfidenceRefinement
	(*ConfidenceRefinementRequest)(nil), // 3: runtime.reasoning.ConfidenceRefinementRequest
	nil,                                 // 4: runtime.reasoning.InferenceTask.ParametersEntry
	(*graph.GraphSnapshot)(nil),         // 5: runtime.graph.GraphSnapshot
	(*hypothesis.AttackHypothesis)(nil), // 6: runtime.hypothesis.AttackHypothesis
}
var file_proto_reasoning_proto_depIdxs = []int32{
	5, // 0: runtime.reasoning.InferenceTask.sub_graph:type_name -> runtime.graph.GraphSnapshot
	4, // 1: runtime.reasoning.InferenceTask.parameters:type_name -> runtime.reasoning.InferenceTask.ParametersEntry
	6, // 2: runtime.reasoning.InferenceResult.hypotheses:type_name -> runtime.hypothesis.AttackHypothesis
	2, // 3: runtime.reasoning.InferenceResult.confidence_updates:type_name -> runtime.reasoning.ConfidenceRefinement
	0, // 4: runtime.reasoning.ReasoningWorker.Infer:input_type -> runtime.reasoning.InferenceTask
	5, // 5: runtime.reasoning.ReasoningWorker.AnalyzeTopology:input_type -> runtime.graph.GraphSnapshot
	3, // 6: runtime.reasoning.ConfidenceEngine.Refine:input_type -> runtime.reasoning.ConfidenceRefinementRequest
	1, // 7: runtime.reasoning.ReasoningWorker.Infer:output_type -> runtime.reasoning.InferenceResult
	1, // 8: runtime.reasoning.ReasoningWorker.AnalyzeTopology:output_type -> runtime.reasoning.InferenceResult
	1, // 9: runtime.reasoning.ConfidenceEngine.Refine:output_type -> runtime.reasoning.InferenceResult
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_reasoning_proto_init() }
func file_proto_reasoning_proto_init() {
	if File_proto_reasoning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reasoning_proto_rawDesc), len(file_proto_reasoning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_reasoning_proto_goTypes,
		DependencyIndexes: file_proto_reasoning_proto_depIdxs,
		MessageInfos:      file_proto_reasoning_proto_msgTypes,
	}.Build()
	File_proto_reasoning_proto = out.File
	file_proto_reasoning_proto_goTypes = nil
	file_proto_reasoning_proto_depIdxs = nil
}
