// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/reasoning.proto

package reasoning

import (
	context "context"
	graph "github.com/hacker/runtime/proto/graph"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReasoningWorker_Infer_FullMethodName           = "/runtime.reasoning.ReasoningWorker/Infer"
	ReasoningWorker_AnalyzeTopology_FullMethodName = "/runtime.reasoning.ReasoningWorker/AnalyzeTopology"
)

// ReasoningWorkerClient is the client API for ReasoningWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReasoningWorkerClient interface {
	Infer(ctx context.Context, in *InferenceTask, opts ...grpc.CallOption) (*InferenceResult, error)
	AnalyzeTopology(ctx context.Context, in *graph.GraphSnapshot, opts ...grpc.CallOption) (*InferenceResult, error)
}

type reasoningWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewReasoningWorkerClient(cc grpc.ClientConnInterface) ReasoningWorkerClient {
	return &reasoningWorkerClient{cc}
}

func (c *reasoningWorkerClient) Infer(ctx context.Context, in *InferenceTask, opts ...grpc.CallOption) (*InferenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResult)
	err := c.cc.Invoke(ctx, ReasoningWorker_Infer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reasoningWorkerClient) AnalyzeTopology(ctx context.Context, in *graph.GraphSnapshot, opts ...grpc.CallOption) (*InferenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResult)
	err := c.cc.Invoke(ctx, ReasoningWorker_AnalyzeTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReasoningWorkerServer is the server API for ReasoningWorker service.
// All implementations must embed UnimplementedReasoningWorkerServer
// for forward compatibility.
type ReasoningWorkerServer interface {
	Infer(context.Context, *InferenceTask) (*InferenceResult, error)
	AnalyzeTopology(context.Context, *graph.GraphSnapshot) (*InferenceResult, error)
	mustEmbedUnimplementedReasoningWorkerServer()
}

// UnimplementedReasoningWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReasoningWorkerServer struct{}

func (UnimplementedReasoningWorkerServer) Infer(context.Context, *InferenceTask) (*InferenceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Infer not implemented")
}
func (UnimplementedReasoningWorkerServer) AnalyzeTopology(context.Context, *graph.GraphSnapshot) (*InferenceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeTopology not implemented")
}
func (UnimplementedReasoningWorkerServer) mustEmbedUnimplementedReasoningWorkerServer() {}
func (UnimplementedReasoningWorkerServer) testEmbeddedByValue()                         {}

// UnsafeReasoningWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReasoningWorkerServer will
// result in compilation errors.
type UnsafeReasoningWorkerServer interface {
	mustEmbedUnimplementedReasoningWorkerServer()
}

func RegisterReasoningWorkerServer(s grpc.ServiceRegistrar, srv ReasoningWorkerServer) {
	// If the following call panics, it indicates UnimplementedReasoningWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReasoningWorker_ServiceDesc, srv)
}

func _ReasoningWorker_Infer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferenceTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningWorkerServer).Infer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningWorker_Infer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningWorkerServer).Infer(ctx, req.(*InferenceTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReasoningWorker_AnalyzeTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(graph.GraphSnapshot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReasoningWorkerServer).AnalyzeTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReasoningWorker_AnalyzeTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReasoningWorkerServer).AnalyzeTopology(ctx, req.(*graph.GraphSnapshot))
	}
	return interceptor(ctx, in, info, handler)
}

// ReasoningWorker_ServiceDesc is the grpc.ServiceDesc for ReasoningWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReasoningWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.reasoning.ReasoningWorker",
	HandlerType: (*ReasoningWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Infer",
			Handler:    _ReasoningWorker_Infer_Handler,
		},
		{
			MethodName: "AnalyzeTopology",
			Handler:    _ReasoningWorker_AnalyzeTopology_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reasoning.proto",
}

const (
	ConfidenceEngine_Refine_FullMethodName = "/runtime.reasoning.ConfidenceEngine/Refine"
)

// ConfidenceEngineClient is the client API for ConfidenceEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfidenceEngineClient interface {
	Refine(ctx context.Context, in *ConfidenceRefinementRequest, opts ...grpc.CallOption) (*InferenceResult, error)
}

type confidenceEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewConfidenceEngineClient(cc grpc.ClientConnInterface) ConfidenceEngineClient {
	return &confidenceEngineClient{cc}
}

func (c *confidenceEngineClient) Refine(ctx context.Context, in *ConfidenceRefinementRequest, opts ...grpc.CallOption) (*InferenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InferenceResult)
	err := c.cc.Invoke(ctx, ConfidenceEngine_Refine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfidenceEngineServer is the server API for ConfidenceEngine service.
// All implementations must embed UnimplementedConfidenceEngineServer
// for forward compatibility.
type ConfidenceEngineServer interface {
	Refine(context.Context, *ConfidenceRefinementRequest) (*InferenceResult, error)
	mustEmbedUnimplementedConfidenceEngineServer()
}

// UnimplementedConfidenceEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfidenceEngineServer struct{}

func (UnimplementedConfidenceEngineServer) Refine(context.Context, *ConfidenceRefinementRequest) (*InferenceResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Refine not implemented")
}
func (UnimplementedConfidenceEngineServer) mustEmbedUnimplementedConfidenceEngineServer() {}
func (UnimplementedConfidenceEngineServer) testEmbeddedByValue()                          {}

// UnsafeConfidenceEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfidenceEngineServer will
// result in compilation errors.
type UnsafeConfidenceEngineServer interface {
	mustEmbedUnimplementedConfidenceEngineServer()
}

func RegisterConfidenceEngineServer(s grpc.ServiceRegistrar, srv ConfidenceEngineServer) {
	// If the following call panics, it indicates UnimplementedConfidenceEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfidenceEngine_ServiceDesc, srv)
}

func _ConfidenceEngine_Refine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfidenceRefinementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfidenceEngineServer).Refine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfidenceEngine_Refine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfidenceEngineServer).Refine(ctx, req.(*ConfidenceRefinementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfidenceEngine_ServiceDesc is the grpc.ServiceDesc for ConfidenceEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfidenceEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.reasoning.ConfidenceEngine",
	HandlerType: (*ConfidenceEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Refine",
			Handler:    _ConfidenceEngine_Refine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reasoning.proto",
}
