// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/signal.proto

package signal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignalIngestion_Ingest_FullMethodName       = "/runtime.signal.SignalIngestion/Ingest"
	SignalIngestion_StreamIngest_FullMethodName = "/runtime.signal.SignalIngestion/StreamIngest"
)

// SignalIngestionClient is the client API for SignalIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalIngestionClient interface {
	Ingest(ctx context.Context, in *ArchitecturalSignal, opts ...grpc.CallOption) (*IngestionResponse, error)
	StreamIngest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArchitecturalSignal, IngestionResponse], error)
}

type signalIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalIngestionClient(cc grpc.ClientConnInterface) SignalIngestionClient {
	return &signalIngestionClient{cc}
}

func (c *signalIngestionClient) Ingest(ctx context.Context, in *ArchitecturalSignal, opts ...grpc.CallOption) (*IngestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestionResponse)
	err := c.cc.Invoke(ctx, SignalIngestion_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalIngestionClient) StreamIngest(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ArchitecturalSignal, IngestionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SignalIngestion_ServiceDesc.Streams[0], SignalIngestion_StreamIngest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArchitecturalSignal, IngestionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalIngestion_StreamIngestClient = grpc.ClientStreamingClient[ArchitecturalSignal, IngestionResponse]

// SignalIngestionServer is the server API for SignalIngestion service.
// All implementations must embed UnimplementedSignalIngestionServer
// for forward compatibility.
type SignalIngestionServer interface {
	Ingest(context.Context, *ArchitecturalSignal) (*IngestionResponse, error)
	StreamIngest(grpc.ClientStreamingServer[ArchitecturalSignal, IngestionResponse]) error
	mustEmbedUnimplementedSignalIngestionServer()
}

// UnimplementedSignalIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignalIngestionServer struct{}

func (UnimplementedSignalIngestionServer) Ingest(context.Context, *ArchitecturalSignal) (*IngestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedSignalIngestionServer) StreamIngest(grpc.ClientStreamingServer[ArchitecturalSignal, IngestionResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamIngest not implemented")
}
func (UnimplementedSignalIngestionServer) mustEmbedUnimplementedSignalIngestionServer() {}
func (UnimplementedSignalIngestionServer) testEmbeddedByValue()                         {}

// UnsafeSignalIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalIngestionServer will
// result in compilation errors.
type UnsafeSignalIngestionServer interface {
	mustEmbedUnimplementedSignalIngestionServer()
}

func RegisterSignalIngestionServer(s grpc.ServiceRegistrar, srv SignalIngestionServer) {
	// If the following call panics, it indicates UnimplementedSignalIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignalIngestion_ServiceDesc, srv)
}

func _SignalIngestion_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchitecturalSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalIngestionServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignalIngestion_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalIngestionServer).Ingest(ctx, req.(*ArchitecturalSignal))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignalIngestion_StreamIngest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignalIngestionServer).StreamIngest(&grpc.GenericServerStream[ArchitecturalSignal, IngestionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SignalIngestion_StreamIngestServer = grpc.ClientStreamingServer[ArchitecturalSignal, IngestionResponse]

// SignalIngestion_ServiceDesc is the grpc.ServiceDesc for SignalIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.signal.SignalIngestion",
	HandlerType: (*SignalIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _SignalIngestion_Ingest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamIngest",
			Handler:       _SignalIngestion_StreamIngest_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/signal.proto",
}
