// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/signal.proto

package signal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArchitecturalSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // e.g., "httpx", "katana", "cloudsploit"
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AssetIdentifier string                 `protobuf:"bytes,4,opt,name=asset_identifier,json=assetIdentifier,proto3" json:"asset_identifier,omitempty"` // URL, IP, ARN, etc.
	// Normalized attributes (e.g., headers, status codes)
	Attributes map[string]string `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Inferred traits (e.g., "uses_graphql", "has_oidc")
	InferredTraits []string        `protobuf:"bytes,6,rep,name=inferred_traits,json=inferredTraits,proto3" json:"inferred_traits,omitempty"`
	Confidence     float32         `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0 to 1.0
	Metadata       *SignalMetadata `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArchitecturalSignal) Reset() {
	*x = ArchitecturalSignal{}
	mi := &file_proto_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchitecturalSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchitecturalSignal) ProtoMessage() {}

func (x *ArchitecturalSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchitecturalSignal.ProtoReflect.Descriptor instead.
func (*ArchitecturalSignal) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{0}
}

func (x *ArchitecturalSignal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArchitecturalSignal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ArchitecturalSignal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ArchitecturalSignal) GetAssetIdentifier() string {
	if x != nil {
		return x.AssetIdentifier
	}
	return ""
}

func (x *ArchitecturalSignal) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ArchitecturalSignal) GetInferredTraits() []string {
	if x != nil {
		return x.InferredTraits
	}
	return nil
}

func (x *ArchitecturalSignal) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ArchitecturalSignal) GetMetadata() *SignalMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SignalMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReasoningTraceId string                 `protobuf:"bytes,1,opt,name=reasoning_trace_id,json=reasoningTraceId,proto3" json:"reasoning_trace_id,omitempty"`
	ProvenanceId     string                 `protobuf:"bytes,2,opt,name=provenance_id,json=provenanceId,proto3" json:"provenance_id,omitempty"` // Links back to raw tool output line
	ToolVersion      string                 `protobuf:"bytes,3,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	ScanSessionId    string                 `protobuf:"bytes,4,opt,name=scan_session_id,json=scanSessionId,proto3" json:"scan_session_id,omitempty"`
	CorrelationIds   map[string]string      `protobuf:"bytes,5,rep,name=correlation_ids,json=correlationIds,proto3" json:"correlation_ids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // e.g., "aws_account_id": "..."
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignalMetadata) Reset() {
	*x = SignalMetadata{}
	mi := &file_proto_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalMetadata) ProtoMessage() {}

func (x *SignalMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalMetadata.ProtoReflect.Descriptor instead.
func (*SignalMetadata) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{1}
}

func (x *SignalMetadata) GetReasoningTraceId() string {
	if x != nil {
		return x.ReasoningTraceId
	}
	return ""
}

func (x *SignalMetadata) GetProvenanceId() string {
	if x != nil {
		return x.ProvenanceId
	}
	return ""
}

func (x *SignalMetadata) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *SignalMetadata) GetScanSessionId() string {
	if x != nil {
		return x.ScanSessionId
	}
	return ""
}

func (x *SignalMetadata) GetCorrelationIds() map[string]string {
	if x != nil {
		return x.CorrelationIds
	}
	return nil
}

type IngestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SignalId      string                 `protobuf:"bytes,3,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionResponse) Reset() {
	*x = IngestionResponse{}
	mi := &file_proto_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionResponse) ProtoMessage() {}

func (x *IngestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionResponse.ProtoReflect.Descriptor instead.
func (*IngestionResponse) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{2}
}

func (x *IngestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *IngestionResponse) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

var File_proto_signal_proto protoreflect.FileDescriptor

const file_proto_signal_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signal.proto\x12\x0eruntime.signal\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x03\n" +
	"\x13ArchitecturalSignal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x10asset_identifier\x18\x04 \x01(\tR\x0fassetIdentifier\x12S\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v23.runtime.signal.ArchitecturalSignal.AttributesEntryR\n" +
	"attributes\x12'\n" +
	"\x0finferred_traits\x18\x06 \x03(\tR\x0einferredTraits\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x12:\n" +
	"\bmetadata\x18\b \x01(\v2\x1e.runtime.signal.SignalMetadataR\bmetadata\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x02\n" +
	"\x0eSignalMetadata\x12,\n" +
	"\x12reasoning_trace_id\x18\x01 \x01(\tR\x10reasoningTraceId\x12#\n" +
	"\rprovenance_id\x18\x02 \x01(\tR\fprovenanceId\x12!\n" +
	"\ftool_version\x18\x03 \x01(\tR\vtoolVersion\x12&\n" +
	"\x0fscan_session_id\x18\x04 \x01(\tR\rscanSessionId\x12[\n" +
	"\x0fcorrelation_ids\x18\x05 \x03(\v22.runtime.signal.SignalMetadata.CorrelationIdsEntryR\x0ecorrelationIds\x1aA\n" +
	"\x13CorrelationIdsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x11IngestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\tsignal_id\x18\x03 \x01(\tR\bsignalId2\xbd\x01\n" +
	"\x0fSignalIngestion\x12P\n" +
	"\x06Ingest\x12#.runtime.signal.ArchitecturalSignal\x1a!.runtime.signal.IngestionResponse\x12X\n" +
	"\fStreamIngest\x12#.runtime.signal.ArchitecturalSignal\x1a!.runtime.signal.IngestionResponse(\x01B(Z&github.com/hacker/runtime/proto/signalb\x06proto3"

var (
	file_proto_signal_proto_rawDescOnce sync.Once
	file_proto_signal_proto_rawDescData []byte
)

func file_proto_signal_proto_rawDescGZIP() []byte {
	file_proto_signal_proto_rawDescOnce.Do(func() {
		file_proto_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)))
	})
	return file_proto_signal_proto_rawDescData
}

var file_proto_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_signal_proto_goTypes = []any{
	(*ArchitecturalSignal)(nil),   // 0: runtime.signal.ArchitecturalSignal
	(*SignalMetadata)(nil),        // 1: runtime.signal.SignalMetadata
	(*IngestionResponse)(nil),     // 2: runtime.signal.IngestionResponse
	nil,                           // 3: runtime.signal.ArchitecturalSignal.AttributesEntry
	nil,                           // 4: runtime.signal.SignalMetadata.CorrelationIdsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_signal_proto_depIdxs = []int32{
	5, // 0: runtime.signal.ArchitecturalSignal.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: runtime.signal.ArchitecturalSignal.attributes:type_name -> runtime.signal.ArchitecturalSignal.AttributesEntry
	1, // 2: runtime.signal.ArchitecturalSignal.metadata:type_name -> runtime.signal.SignalMetadata
	4, // 3: runtime.signal.SignalMetadata.correlation_ids:type_name -> runtime.signal.SignalMetadata.CorrelationIdsEntry
	0, // 4: runtime.signal.SignalIngestion.Ingest:input_type -> runtime.signal.ArchitecturalSignal
	0, // 5: runtime.signal.SignalIngestion.StreamIngest:input_type -> runtime.signal.ArchitecturalSignal
	2, // 6: runtime.signal.SignalIngestion.Ingest:output_type -> runtime.signal.IngestionResponse
	2, // 7: runtime.signal.SignalIngestion.StreamIngest:output_type -> runtime.signal.IngestionResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_signal_proto_init() }
func file_proto_signal_proto_init() {
	if File_proto_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signal_proto_goTypes,
		DependencyIndexes: file_proto_signal_proto_depIdxs,
		MessageInfos:      file_proto_signal_proto_msgTypes,
	}.Build()
	File_proto_signal_proto = out.File
	file_proto_signal_proto_goTypes = nil
	file_proto_signal_proto_depIdxs = nil
}
