// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/orchestration.proto

package orchestration

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrchestrationCore_StartSession_FullMethodName  = "/runtime.orchestration.OrchestrationCore/StartSession"
	OrchestrationCore_StopSession_FullMethodName   = "/runtime.orchestration.OrchestrationCore/StopSession"
	OrchestrationCore_GetStatus_FullMethodName     = "/runtime.orchestration.OrchestrationCore/GetStatus"
	OrchestrationCore_TriggerReplay_FullMethodName = "/runtime.orchestration.OrchestrationCore/TriggerReplay"
)

// OrchestrationCoreClient is the client API for OrchestrationCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrchestrationCoreClient interface {
	StartSession(ctx context.Context, in *SessionConfig, opts ...grpc.CallOption) (*RuntimeStatus, error)
	StopSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*RuntimeStatus, error)
	GetStatus(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*RuntimeStatus, error)
	TriggerReplay(ctx context.Context, in *ReplaySession, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeStatus], error)
}

type orchestrationCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestrationCoreClient(cc grpc.ClientConnInterface) OrchestrationCoreClient {
	return &orchestrationCoreClient{cc}
}

func (c *orchestrationCoreClient) StartSession(ctx context.Context, in *SessionConfig, opts ...grpc.CallOption) (*RuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeStatus)
	err := c.cc.Invoke(ctx, OrchestrationCore_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationCoreClient) StopSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*RuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeStatus)
	err := c.cc.Invoke(ctx, OrchestrationCore_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationCoreClient) GetStatus(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*RuntimeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeStatus)
	err := c.cc.Invoke(ctx, OrchestrationCore_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestrationCoreClient) TriggerReplay(ctx context.Context, in *ReplaySession, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RuntimeStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrchestrationCore_ServiceDesc.Streams[0], OrchestrationCore_TriggerReplay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplaySession, RuntimeStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationCore_TriggerReplayClient = grpc.ServerStreamingClient[RuntimeStatus]

// OrchestrationCoreServer is the server API for OrchestrationCore service.
// All implementations must embed UnimplementedOrchestrationCoreServer
// for forward compatibility.
type OrchestrationCoreServer interface {
	StartSession(context.Context, *SessionConfig) (*RuntimeStatus, error)
	StopSession(context.Context, *SessionRequest) (*RuntimeStatus, error)
	GetStatus(context.Context, *SessionRequest) (*RuntimeStatus, error)
	TriggerReplay(*ReplaySession, grpc.ServerStreamingServer[RuntimeStatus]) error
	mustEmbedUnimplementedOrchestrationCoreServer()
}

// UnimplementedOrchestrationCoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestrationCoreServer struct{}

func (UnimplementedOrchestrationCoreServer) StartSession(context.Context, *SessionConfig) (*RuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedOrchestrationCoreServer) StopSession(context.Context, *SessionRequest) (*RuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedOrchestrationCoreServer) GetStatus(context.Context, *SessionRequest) (*RuntimeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedOrchestrationCoreServer) TriggerReplay(*ReplaySession, grpc.ServerStreamingServer[RuntimeStatus]) error {
	return status.Error(codes.Unimplemented, "method TriggerReplay not implemented")
}
func (UnimplementedOrchestrationCoreServer) mustEmbedUnimplementedOrchestrationCoreServer() {}
func (UnimplementedOrchestrationCoreServer) testEmbeddedByValue()                           {}

// UnsafeOrchestrationCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestrationCoreServer will
// result in compilation errors.
type UnsafeOrchestrationCoreServer interface {
	mustEmbedUnimplementedOrchestrationCoreServer()
}

func RegisterOrchestrationCoreServer(s grpc.ServiceRegistrar, srv OrchestrationCoreServer) {
	// If the following call panics, it indicates UnimplementedOrchestrationCoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestrationCore_ServiceDesc, srv)
}

func _OrchestrationCore_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationCoreServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationCore_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationCoreServer).StartSession(ctx, req.(*SessionConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationCore_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationCoreServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationCore_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationCoreServer).StopSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationCore_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestrationCoreServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestrationCore_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestrationCoreServer).GetStatus(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestrationCore_TriggerReplay_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplaySession)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrchestrationCoreServer).TriggerReplay(m, &grpc.GenericServerStream[ReplaySession, RuntimeStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrchestrationCore_TriggerReplayServer = grpc.ServerStreamingServer[RuntimeStatus]

// OrchestrationCore_ServiceDesc is the grpc.ServiceDesc for OrchestrationCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestrationCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.orchestration.OrchestrationCore",
	HandlerType: (*OrchestrationCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _OrchestrationCore_StartSession_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _OrchestrationCore_StopSession_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _OrchestrationCore_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TriggerReplay",
			Handler:       _OrchestrationCore_TriggerReplay_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/orchestration.proto",
}
