// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/orchestration.proto

package orchestration

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleState int32

const (
	LifecycleState_INITIALIZING LifecycleState = 0
	LifecycleState_STREAMING    LifecycleState = 1
	LifecycleState_CONVERGING   LifecycleState = 2
	LifecycleState_HIBERNATING  LifecycleState = 3
	LifecycleState_ERROR        LifecycleState = 4
)

// Enum value maps for LifecycleState.
var (
	LifecycleState_name = map[int32]string{
		0: "INITIALIZING",
		1: "STREAMING",
		2: "CONVERGING",
		3: "HIBERNATING",
		4: "ERROR",
	}
	LifecycleState_value = map[string]int32{
		"INITIALIZING": 0,
		"STREAMING":    1,
		"CONVERGING":   2,
		"HIBERNATING":  3,
		"ERROR":        4,
	}
)

func (x LifecycleState) Enum() *LifecycleState {
	p := new(LifecycleState)
	*p = x
	return p
}

func (x LifecycleState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestration_proto_enumTypes[0].Descriptor()
}

func (LifecycleState) Type() protoreflect.EnumType {
	return &file_proto_orchestration_proto_enumTypes[0]
}

func (x LifecycleState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleState.Descriptor instead.
func (LifecycleState) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{0}
}

type ReplaySession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartSequence int64                  `protobuf:"varint,2,opt,name=start_sequence,json=startSequence,proto3" json:"start_sequence,omitempty"`
	EndSequence   int64                  `protobuf:"varint,3,opt,name=end_sequence,json=endSequence,proto3" json:"end_sequence,omitempty"`
	ReplaySpeed   float32                `protobuf:"fixed32,4,opt,name=replay_speed,json=replaySpeed,proto3" json:"replay_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaySession) Reset() {
	*x = ReplaySession{}
	mi := &file_proto_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaySession) ProtoMessage() {}

func (x *ReplaySession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaySession.ProtoReflect.Descriptor instead.
func (*ReplaySession) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *ReplaySession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReplaySession) GetStartSequence() int64 {
	if x != nil {
		return x.StartSequence
	}
	return 0
}

func (x *ReplaySession) GetEndSequence() int64 {
	if x != nil {
		return x.EndSequence
	}
	return 0
}

func (x *ReplaySession) GetReplaySpeed() float32 {
	if x != nil {
		return x.ReplaySpeed
	}
	return 0
}

type IngestionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalId      string                 `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionEvent) Reset() {
	*x = IngestionEvent{}
	mi := &file_proto_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionEvent) ProtoMessage() {}

func (x *IngestionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionEvent.ProtoReflect.Descriptor instead.
func (*IngestionEvent) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *IngestionEvent) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *IngestionEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IngestionEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GraphUpdateEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaId       string                 `protobuf:"bytes,1,opt,name=delta_id,json=deltaId,proto3" json:"delta_id,omitempty"`
	NodesAffected int32                  `protobuf:"varint,2,opt,name=nodes_affected,json=nodesAffected,proto3" json:"nodes_affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphUpdateEvent) Reset() {
	*x = GraphUpdateEvent{}
	mi := &file_proto_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphUpdateEvent) ProtoMessage() {}

func (x *GraphUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphUpdateEvent.ProtoReflect.Descriptor instead.
func (*GraphUpdateEvent) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *GraphUpdateEvent) GetDeltaId() string {
	if x != nil {
		return x.DeltaId
	}
	return ""
}

func (x *GraphUpdateEvent) GetNodesAffected() int32 {
	if x != nil {
		return x.NodesAffected
	}
	return 0
}

type RuntimeStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State             LifecycleState         `protobuf:"varint,2,opt,name=state,proto3,enum=runtime.orchestration.LifecycleState" json:"state,omitempty"`
	EventCount        int64                  `protobuf:"varint,3,opt,name=event_count,json=eventCount,proto3" json:"event_count,omitempty"`
	ConfidenceAverage float32                `protobuf:"fixed32,4,opt,name=confidence_average,json=confidenceAverage,proto3" json:"confidence_average,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeStatus) Reset() {
	*x = RuntimeStatus{}
	mi := &file_proto_orchestration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStatus) ProtoMessage() {}

func (x *RuntimeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStatus.ProtoReflect.Descriptor instead.
func (*RuntimeStatus) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RuntimeStatus) GetState() LifecycleState {
	if x != nil {
		return x.State
	}
	return LifecycleState_INITIALIZING
}

func (x *RuntimeStatus) GetEventCount() int64 {
	if x != nil {
		return x.EventCount
	}
	return 0
}

func (x *RuntimeStatus) GetConfidenceAverage() float32 {
	if x != nil {
		return x.ConfidenceAverage
	}
	return 0
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_proto_orchestration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{4}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EnvironmentParams map[string]string      `protobuf:"bytes,2,rep,name=environment_params,json=environmentParams,proto3" json:"environment_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_proto_orchestration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_proto_orchestration_proto_rawDescGZIP(), []int{5}
}

func (x *SessionConfig) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionConfig) GetEnvironmentParams() map[string]string {
	if x != nil {
		return x.EnvironmentParams
	}
	return nil
}

var File_proto_orchestration_proto protoreflect.FileDescriptor

const file_proto_orchestration_proto_rawDesc = "" +
	"\n" +
	"\x19proto/orchestration.proto\x12\x15runtime.orchestration\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\rReplaySession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0estart_sequence\x18\x02 \x01(\x03R\rstartSequence\x12!\n" +
	"\fend_sequence\x18\x03 \x01(\x03R\vendSequence\x12!\n" +
	"\freplay_speed\x18\x04 \x01(\x02R\vreplaySpeed\"\x7f\n" +
	"\x0eIngestionEvent\x12\x1b\n" +
	"\tsignal_id\x18\x01 \x01(\tR\bsignalId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"T\n" +
	"\x10GraphUpdateEvent\x12\x19\n" +
	"\bdelta_id\x18\x01 \x01(\tR\adeltaId\x12%\n" +
	"\x0enodes_affected\x18\x02 \x01(\x05R\rnodesAffected\"\xbb\x01\n" +
	"\rRuntimeStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\x05state\x18\x02 \x01(\x0e2%.runtime.orchestration.LifecycleStateR\x05state\x12\x1f\n" +
	"\vevent_count\x18\x03 \x01(\x03R\n" +
	"eventCount\x12-\n" +
	"\x12confidence_average\x18\x04 \x01(\x02R\x11confidenceAverage\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xe0\x01\n" +
	"\rSessionConfig\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12j\n" +
	"\x12environment_params\x18\x02 \x03(\v2;.runtime.orchestration.SessionConfig.EnvironmentParamsEntryR\x11environmentParams\x1aD\n" +
	"\x16EnvironmentParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*]\n" +
	"\x0eLifecycleState\x12\x10\n" +
	"\fINITIALIZING\x10\x00\x12\r\n" +
	"\tSTREAMING\x10\x01\x12\x0e\n" +
	"\n" +
	"CONVERGING\x10\x02\x12\x0f\n" +
	"\vHIBERNATING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x042\x84\x03\n" +
	"\x11OrchestrationCore\x12Z\n" +
	"\fStartSession\x12$.runtime.orchestration.SessionConfig\x1a$.runtime.orchestration.RuntimeStatus\x12Z\n" +
	"\vStopSession\x12%.runtime.orchestration.SessionRequest\x1a$.runtime.orchestration.RuntimeStatus\x12X\n" +
	"\tGetStatus\x12%.runtime.orchestration.SessionRequest\x1a$.runtime.orchestration.RuntimeStatus\x12]\n" +
	"\rTriggerReplay\x12$.runtime.orchestration.ReplaySession\x1a$.runtime.orchestration.RuntimeStatus0\x01B/Z-github.com/hacker/runtime/proto/orchestrationb\x06proto3"

var (
	file_proto_orchestration_proto_rawDescOnce sync.Once
	file_proto_orchestration_proto_rawDescData []byte
)

func file_proto_orchestration_proto_rawDescGZIP() []byte {
	file_proto_orchestration_proto_rawDescOnce.Do(func() {
		file_proto_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestration_proto_rawDesc), len(file_proto_orchestration_proto_rawDesc)))
	})
	return file_proto_orchestration_proto_rawDescData
}

var file_proto_orchestration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_orchestration_proto_goTypes = []any{
	(LifecycleState)(0),           // 0: runtime.orchestration.LifecycleState
	(*ReplaySession)(nil),         // 1: runtime.orchestration.ReplaySession
	(*IngestionEvent)(nil),        // 2: runtime.orchestration.IngestionEvent
	(*GraphUpdateEvent)(nil),      // 3: runtime.orchestration.GraphUpdateEvent
	(*RuntimeStatus)(nil),         // 4: runtime.orchestration.RuntimeStatus
	(*SessionRequest)(nil),        // 5: runtime.orchestration.SessionRequest
	(*SessionConfig)(nil),         // 6: runtime.orchestration.SessionConfig
	nil,                           // 7: runtime.orchestration.SessionConfig.EnvironmentParamsEntry
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_proto_orchestration_proto_depIdxs = []int32{
	8, // 0: runtime.orchestration.IngestionEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: runtime.orchestration.RuntimeStatus.state:type_name -> runtime.orchestration.LifecycleState
	7, // 2: runtime.orchestration.SessionConfig.environment_params:type_name -> runtime.orchestration.SessionConfig.EnvironmentParamsEntry
	6, // 3: runtime.orchestration.OrchestrationCore.StartSession:input_type -> runtime.orchestration.SessionConfig
	5, // 4: runtime.orchestration.OrchestrationCore.StopSession:input_type -> runtime.orchestration.SessionRequest
	5, // 5: runtime.orchestration.OrchestrationCore.GetStatus:input_type -> runtime.orchestration.SessionRequest
	1, // 6: runtime.orchestration.OrchestrationCore.TriggerReplay:input_type -> runtime.orchestration.ReplaySession
	4, // 7: runtime.orchestration.OrchestrationCore.StartSession:output_type -> runtime.orchestration.RuntimeStatus
	4, // 8: runtime.orchestration.OrchestrationCore.StopSession:output_type -> runtime.orchestration.RuntimeStatus
	4, // 9: runtime.orchestration.OrchestrationCore.GetStatus:output_type -> runtime.orchestration.RuntimeStatus
	4, // 10: runtime.orchestration.OrchestrationCore.TriggerReplay:output_type -> runtime.orchestration.RuntimeStatus
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_orchestration_proto_init() }
func file_proto_orchestration_proto_init() {
	if File_proto_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestration_proto_rawDesc), len(file_proto_orchestration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestration_proto_goTypes,
		DependencyIndexes: file_proto_orchestration_proto_depIdxs,
		EnumInfos:         file_proto_orchestration_proto_enumTypes,
		MessageInfos:      file_proto_orchestration_proto_msgTypes,
	}.Build()
	File_proto_orchestration_proto = out.File
	file_proto_orchestration_proto_goTypes = nil
	file_proto_orchestration_proto_depIdxs = nil
}
