// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/graph.proto

package graph

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeType int32

const (
	NodeType_UNKNOWN_NODE      NodeType = 0
	NodeType_GATEWAY           NodeType = 1
	NodeType_PARSER_BOUNDARY   NodeType = 2
	NodeType_IDENTITY_BOUNDARY NodeType = 3
	NodeType_ASYNC_WORKFLOW    NodeType = 4
	NodeType_DISTRIBUTED_STATE NodeType = 5
	NodeType_WORKLOAD_IDENTITY NodeType = 6
	NodeType_TRUST_BOUNDARY    NodeType = 7
	NodeType_INTERNAL_SERVICE  NodeType = 8
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "UNKNOWN_NODE",
		1: "GATEWAY",
		2: "PARSER_BOUNDARY",
		3: "IDENTITY_BOUNDARY",
		4: "ASYNC_WORKFLOW",
		5: "DISTRIBUTED_STATE",
		6: "WORKLOAD_IDENTITY",
		7: "TRUST_BOUNDARY",
		8: "INTERNAL_SERVICE",
	}
	NodeType_value = map[string]int32{
		"UNKNOWN_NODE":      0,
		"GATEWAY":           1,
		"PARSER_BOUNDARY":   2,
		"IDENTITY_BOUNDARY": 3,
		"ASYNC_WORKFLOW":    4,
		"DISTRIBUTED_STATE": 5,
		"WORKLOAD_IDENTITY": 6,
		"TRUST_BOUNDARY":    7,
		"INTERNAL_SERVICE":  8,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_graph_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_proto_graph_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{0}
}

type EdgeType int32

const (
	EdgeType_UNKNOWN_EDGE         EdgeType = 0
	EdgeType_PROTOCOL_TRANSLATION EdgeType = 1
	EdgeType_IDENTITY_PROPAGATION EdgeType = 2
	EdgeType_ASYNC_EXECUTION      EdgeType = 3
	EdgeType_STATE_REPLICATION    EdgeType = 4
	EdgeType_PARSER_TRANSITION    EdgeType = 5
	EdgeType_DELEGATED_TRUST      EdgeType = 6
	EdgeType_NETWORK_FLOW         EdgeType = 7
)

// Enum value maps for EdgeType.
var (
	EdgeType_name = map[int32]string{
		0: "UNKNOWN_EDGE",
		1: "PROTOCOL_TRANSLATION",
		2: "IDENTITY_PROPAGATION",
		3: "ASYNC_EXECUTION",
		4: "STATE_REPLICATION",
		5: "PARSER_TRANSITION",
		6: "DELEGATED_TRUST",
		7: "NETWORK_FLOW",
	}
	EdgeType_value = map[string]int32{
		"UNKNOWN_EDGE":         0,
		"PROTOCOL_TRANSLATION": 1,
		"IDENTITY_PROPAGATION": 2,
		"ASYNC_EXECUTION":      3,
		"STATE_REPLICATION":    4,
		"PARSER_TRANSITION":    5,
		"DELEGATED_TRUST":      6,
		"NETWORK_FLOW":         7,
	}
)

func (x EdgeType) Enum() *EdgeType {
	p := new(EdgeType)
	*p = x
	return p
}

func (x EdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_graph_proto_enumTypes[1].Descriptor()
}

func (EdgeType) Type() protoreflect.EnumType {
	return &file_proto_graph_proto_enumTypes[1]
}

func (x EdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeType.Descriptor instead.
func (EdgeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{1}
}

type Node struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=runtime.graph.NodeType" json:"type,omitempty"`
	Layer           string                 `protobuf:"bytes,3,opt,name=layer,proto3" json:"layer,omitempty"` // physical, identity, mechanism
	Labels          []string               `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Properties      map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfidenceScore float32                `protobuf:"fixed32,6,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	FirstSeen       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	EvidenceIds     []string               `protobuf:"bytes,9,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_proto_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_UNKNOWN_NODE
}

func (x *Node) GetLayer() string {
	if x != nil {
		return x.Layer
	}
	return ""
}

func (x *Node) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Node) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Node) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *Node) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Node) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Node) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

type Edge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId        string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId        string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Type            EdgeType               `protobuf:"varint,4,opt,name=type,proto3,enum=runtime.graph.EdgeType" json:"type,omitempty"`
	Properties      map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConfidenceScore float32                `protobuf:"fixed32,6,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	EvidenceIds     []string               `protobuf:"bytes,7,rep,name=evidence_ids,json=evidenceIds,proto3" json:"evidence_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_proto_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Edge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Edge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *Edge) GetType() EdgeType {
	if x != nil {
		return x.Type
	}
	return EdgeType_UNKNOWN_EDGE
}

func (x *Edge) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Edge) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *Edge) GetEvidenceIds() []string {
	if x != nil {
		return x.EvidenceIds
	}
	return nil
}

type GraphSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nodes         []*Node                `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,5,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphSnapshot) Reset() {
	*x = GraphSnapshot{}
	mi := &file_proto_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphSnapshot) ProtoMessage() {}

func (x *GraphSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphSnapshot.ProtoReflect.Descriptor instead.
func (*GraphSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{2}
}

func (x *GraphSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GraphSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *GraphSnapshot) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphSnapshot) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphDelta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentSnapshotId string                 `protobuf:"bytes,2,opt,name=parent_snapshot_id,json=parentSnapshotId,proto3" json:"parent_snapshot_id,omitempty"`
	AddedNodes       []*Node                `protobuf:"bytes,3,rep,name=added_nodes,json=addedNodes,proto3" json:"added_nodes,omitempty"`
	UpdatedNodes     []*Node                `protobuf:"bytes,4,rep,name=updated_nodes,json=updatedNodes,proto3" json:"updated_nodes,omitempty"`
	RemovedNodeIds   []string               `protobuf:"bytes,5,rep,name=removed_node_ids,json=removedNodeIds,proto3" json:"removed_node_ids,omitempty"`
	AddedEdges       []*Edge                `protobuf:"bytes,6,rep,name=added_edges,json=addedEdges,proto3" json:"added_edges,omitempty"`
	UpdatedEdges     []*Edge                `protobuf:"bytes,7,rep,name=updated_edges,json=updatedEdges,proto3" json:"updated_edges,omitempty"`
	RemovedEdgeIds   []string               `protobuf:"bytes,8,rep,name=removed_edge_ids,json=removedEdgeIds,proto3" json:"removed_edge_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GraphDelta) Reset() {
	*x = GraphDelta{}
	mi := &file_proto_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphDelta) ProtoMessage() {}

func (x *GraphDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphDelta.ProtoReflect.Descriptor instead.
func (*GraphDelta) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{3}
}

func (x *GraphDelta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphDelta) GetParentSnapshotId() string {
	if x != nil {
		return x.ParentSnapshotId
	}
	return ""
}

func (x *GraphDelta) GetAddedNodes() []*Node {
	if x != nil {
		return x.AddedNodes
	}
	return nil
}

func (x *GraphDelta) GetUpdatedNodes() []*Node {
	if x != nil {
		return x.UpdatedNodes
	}
	return nil
}

func (x *GraphDelta) GetRemovedNodeIds() []string {
	if x != nil {
		return x.RemovedNodeIds
	}
	return nil
}

func (x *GraphDelta) GetAddedEdges() []*Edge {
	if x != nil {
		return x.AddedEdges
	}
	return nil
}

func (x *GraphDelta) GetUpdatedEdges() []*Edge {
	if x != nil {
		return x.UpdatedEdges
	}
	return nil
}

func (x *GraphDelta) GetRemovedEdgeIds() []string {
	if x != nil {
		return x.RemovedEdgeIds
	}
	return nil
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AsOf          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=as_of,json=asOf,proto3" json:"as_of,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_proto_graph_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{4}
}

func (x *SnapshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SnapshotRequest) GetAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.AsOf
	}
	return nil
}

type GraphQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryString   string                 `protobuf:"bytes,1,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphQuery) Reset() {
	*x = GraphQuery{}
	mi := &file_proto_graph_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphQuery) ProtoMessage() {}

func (x *GraphQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphQuery.ProtoReflect.Descriptor instead.
func (*GraphQuery) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{5}
}

func (x *GraphQuery) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *GraphQuery) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type GraphResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphResponse) Reset() {
	*x = GraphResponse{}
	mi := &file_proto_graph_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphResponse) ProtoMessage() {}

func (x *GraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphResponse.ProtoReflect.Descriptor instead.
func (*GraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{6}
}

func (x *GraphResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GraphResponse) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	NewSnapshotId string                 `protobuf:"bytes,3,opt,name=new_snapshot_id,json=newSnapshotId,proto3" json:"new_snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_graph_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_graph_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_graph_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpdateResponse) GetNewSnapshotId() string {
	if x != nil {
		return x.NewSnapshotId
	}
	return ""
}

var File_proto_graph_proto protoreflect.FileDescriptor

const file_proto_graph_proto_rawDesc = "" +
	"\n" +
	"\x11proto/graph.proto\x12\rruntime.graph\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x03\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04type\x18\x02 \x01(\x0e2\x17.runtime.graph.NodeTypeR\x04type\x12\x14\n" +
	"\x05layer\x18\x03 \x01(\tR\x05layer\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12C\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2#.runtime.graph.Node.PropertiesEntryR\n" +
	"properties\x12)\n" +
	"\x10confidence_score\x18\x06 \x01(\x02R\x0fconfidenceScore\x129\n" +
	"\n" +
	"first_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12!\n" +
	"\fevidence_ids\x18\t \x03(\tR\vevidenceIds\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x02\n" +
	"\x04Edge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12+\n" +
	"\x04type\x18\x04 \x01(\x0e2\x17.runtime.graph.EdgeTypeR\x04type\x12C\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2#.runtime.graph.Edge.PropertiesEntryR\n" +
	"properties\x12)\n" +
	"\x10confidence_score\x18\x06 \x01(\x02R\x0fconfidenceScore\x12!\n" +
	"\fevidence_ids\x18\a \x03(\tR\vevidenceIds\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\rGraphSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12)\n" +
	"\x05nodes\x18\x04 \x03(\v2\x13.runtime.graph.NodeR\x05nodes\x12)\n" +
	"\x05edges\x18\x05 \x03(\v2\x13.runtime.graph.EdgeR\x05edges\"\xfe\x02\n" +
	"\n" +
	"GraphDelta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12parent_snapshot_id\x18\x02 \x01(\tR\x10parentSnapshotId\x124\n" +
	"\vadded_nodes\x18\x03 \x03(\v2\x13.runtime.graph.NodeR\n" +
	"addedNodes\x128\n" +
	"\rupdated_nodes\x18\x04 \x03(\v2\x13.runtime.graph.NodeR\fupdatedNodes\x12(\n" +
	"\x10removed_node_ids\x18\x05 \x03(\tR\x0eremovedNodeIds\x124\n" +
	"\vadded_edges\x18\x06 \x03(\v2\x13.runtime.graph.EdgeR\n" +
	"addedEdges\x128\n" +
	"\rupdated_edges\x18\a \x03(\v2\x13.runtime.graph.EdgeR\fupdatedEdges\x12(\n" +
	"\x10removed_edge_ids\x18\b \x03(\tR\x0eremovedEdgeIds\"a\n" +
	"\x0fSnapshotRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x05as_of\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04asOf\"\xb9\x01\n" +
	"\n" +
	"GraphQuery\x12!\n" +
	"\fquery_string\x18\x01 \x01(\tR\vqueryString\x12I\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2).runtime.graph.GraphQuery.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\rGraphResponse\x12)\n" +
	"\x05nodes\x18\x01 \x03(\v2\x13.runtime.graph.NodeR\x05nodes\x12)\n" +
	"\x05edges\x18\x02 \x03(\v2\x13.runtime.graph.EdgeR\x05edges\"w\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12&\n" +
	"\x0fnew_snapshot_id\x18\x03 \x01(\tR\rnewSnapshotId*\xc1\x01\n" +
	"\bNodeType\x12\x10\n" +
	"\fUNKNOWN_NODE\x10\x00\x12\v\n" +
	"\aGATEWAY\x10\x01\x12\x13\n" +
	"\x0fPARSER_BOUNDARY\x10\x02\x12\x15\n" +
	"\x11IDENTITY_BOUNDARY\x10\x03\x12\x12\n" +
	"\x0eASYNC_WORKFLOW\x10\x04\x12\x15\n" +
	"\x11DISTRIBUTED_STATE\x10\x05\x12\x15\n" +
	"\x11WORKLOAD_IDENTITY\x10\x06\x12\x12\n" +
	"\x0eTRUST_BOUNDARY\x10\a\x12\x14\n" +
	"\x10INTERNAL_SERVICE\x10\b*\xba\x01\n" +
	"\bEdgeType\x12\x10\n" +
	"\fUNKNOWN_EDGE\x10\x00\x12\x18\n" +
	"\x14PROTOCOL_TRANSLATION\x10\x01\x12\x18\n" +
	"\x14IDENTITY_PROPAGATION\x10\x02\x12\x13\n" +
	"\x0fASYNC_EXECUTION\x10\x03\x12\x15\n" +
	"\x11STATE_REPLICATION\x10\x04\x12\x15\n" +
	"\x11PARSER_TRANSITION\x10\x05\x12\x13\n" +
	"\x0fDELEGATED_TRUST\x10\x06\x12\x10\n" +
	"\fNETWORK_FLOW\x10\a2\xe9\x01\n" +
	"\vGraphEngine\x12K\n" +
	"\vGetSnapshot\x12\x1e.runtime.graph.SnapshotRequest\x1a\x1c.runtime.graph.GraphSnapshot\x12F\n" +
	"\n" +
	"ApplyDelta\x12\x19.runtime.graph.GraphDelta\x1a\x1d.runtime.graph.UpdateResponse\x12E\n" +
	"\n" +
	"QueryGraph\x12\x19.runtime.graph.GraphQuery\x1a\x1c.runtime.graph.GraphResponseB'Z%github.com/hacker/runtime/proto/graphb\x06proto3"

var (
	file_proto_graph_proto_rawDescOnce sync.Once
	file_proto_graph_proto_rawDescData []byte
)

func file_proto_graph_proto_rawDescGZIP() []byte {
	file_proto_graph_proto_rawDescOnce.Do(func() {
		file_proto_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)))
	})
	return file_proto_graph_proto_rawDescData
}

var file_proto_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_graph_proto_goTypes = []any{
	(NodeType)(0),                 // 0: runtime.graph.NodeType
	(EdgeType)(0),                 // 1: runtime.graph.EdgeType
	(*Node)(nil),                  // 2: runtime.graph.Node
	(*Edge)(nil),                  // 3: runtime.graph.Edge
	(*GraphSnapshot)(nil),         // 4: runtime.graph.GraphSnapshot
	(*GraphDelta)(nil),            // 5: runtime.graph.GraphDelta
	(*SnapshotRequest)(nil),       // 6: runtime.graph.SnapshotRequest
	(*GraphQuery)(nil),            // 7: runtime.graph.GraphQuery
	(*GraphResponse)(nil),         // 8: runtime.graph.GraphResponse
	(*UpdateResponse)(nil),        // 9: runtime.graph.UpdateResponse
	nil,                           // 10: runtime.graph.Node.PropertiesEntry
	nil,                           // 11: runtime.graph.Edge.PropertiesEntry
	nil,                           // 12: runtime.graph.GraphQuery.ParametersEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_proto_graph_proto_depIdxs = []int32{
	0,  // 0: runtime.graph.Node.type:type_name -> runtime.graph.NodeType
	10, // 1: runtime.graph.Node.properties:type_name -> runtime.graph.Node.PropertiesEntry
	13, // 2: runtime.graph.Node.first_seen:type_name -> google.protobuf.Timestamp
	13, // 3: runtime.graph.Node.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 4: runtime.graph.Edge.type:type_name -> runtime.graph.EdgeType
	11, // 5: runtime.graph.Edge.properties:type_name -> runtime.graph.Edge.PropertiesEntry
	13, // 6: runtime.graph.GraphSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 7: runtime.graph.GraphSnapshot.nodes:type_name -> runtime.graph.Node
	3,  // 8: runtime.graph.GraphSnapshot.edges:type_name -> runtime.graph.Edge
	2,  // 9: runtime.graph.GraphDelta.added_nodes:type_name -> runtime.graph.Node
	2,  // 10: runtime.graph.GraphDelta.updated_nodes:type_name -> runtime.graph.Node
	3,  // 11: runtime.graph.GraphDelta.added_edges:type_name -> runtime.graph.Edge
	3,  // 12: runtime.graph.GraphDelta.updated_edges:type_name -> runtime.graph.Edge
	13, // 13: runtime.graph.SnapshotRequest.as_of:type_name -> google.protobuf.Timestamp
	12, // 14: runtime.graph.GraphQuery.parameters:type_name -> runtime.graph.GraphQuery.ParametersEntry
	2,  // 15: runtime.graph.GraphResponse.nodes:type_name -> runtime.graph.Node
	3,  // 16: runtime.graph.GraphResponse.edges:type_name -> runtime.graph.Edge
	6,  // 17: runtime.graph.GraphEngine.GetSnapshot:input_type -> runtime.graph.SnapshotRequest
	5,  // 18: runtime.graph.GraphEngine.ApplyDelta:input_type -> runtime.graph.GraphDelta
	7,  // 19: runtime.graph.GraphEngine.QueryGraph:input_type -> runtime.graph.GraphQuery
	4,  // 20: runtime.graph.GraphEngine.GetSnapshot:output_type -> runtime.graph.GraphSnapshot
	9,  // 21: runtime.graph.GraphEngine.ApplyDelta:output_type -> runtime.graph.UpdateResponse
	8,  // 22: runtime.graph.GraphEngine.QueryGraph:output_type -> runtime.graph.GraphResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_graph_proto_init() }
func file_proto_graph_proto_init() {
	if File_proto_graph_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_graph_proto_rawDesc), len(file_proto_graph_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_graph_proto_goTypes,
		DependencyIndexes: file_proto_graph_proto_depIdxs,
		EnumInfos:         file_proto_graph_proto_enumTypes,
		MessageInfos:      file_proto_graph_proto_msgTypes,
	}.Build()
	File_proto_graph_proto = out.File
	file_proto_graph_proto_goTypes = nil
	file_proto_graph_proto_depIdxs = nil
}
