// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/graph.proto

package graph

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphEngine_GetSnapshot_FullMethodName = "/runtime.graph.GraphEngine/GetSnapshot"
	GraphEngine_ApplyDelta_FullMethodName  = "/runtime.graph.GraphEngine/ApplyDelta"
	GraphEngine_QueryGraph_FullMethodName  = "/runtime.graph.GraphEngine/QueryGraph"
)

// GraphEngineClient is the client API for GraphEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphEngineClient interface {
	GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*GraphSnapshot, error)
	ApplyDelta(ctx context.Context, in *GraphDelta, opts ...grpc.CallOption) (*UpdateResponse, error)
	QueryGraph(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (*GraphResponse, error)
}

type graphEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphEngineClient(cc grpc.ClientConnInterface) GraphEngineClient {
	return &graphEngineClient{cc}
}

func (c *graphEngineClient) GetSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*GraphSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphSnapshot)
	err := c.cc.Invoke(ctx, GraphEngine_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphEngineClient) ApplyDelta(ctx context.Context, in *GraphDelta, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, GraphEngine_ApplyDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphEngineClient) QueryGraph(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (*GraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphResponse)
	err := c.cc.Invoke(ctx, GraphEngine_QueryGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphEngineServer is the server API for GraphEngine service.
// All implementations must embed UnimplementedGraphEngineServer
// for forward compatibility.
type GraphEngineServer interface {
	GetSnapshot(context.Context, *SnapshotRequest) (*GraphSnapshot, error)
	ApplyDelta(context.Context, *GraphDelta) (*UpdateResponse, error)
	QueryGraph(context.Context, *GraphQuery) (*GraphResponse, error)
	mustEmbedUnimplementedGraphEngineServer()
}

// UnimplementedGraphEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphEngineServer struct{}

func (UnimplementedGraphEngineServer) GetSnapshot(context.Context, *SnapshotRequest) (*GraphSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedGraphEngineServer) ApplyDelta(context.Context, *GraphDelta) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyDelta not implemented")
}
func (UnimplementedGraphEngineServer) QueryGraph(context.Context, *GraphQuery) (*GraphResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryGraph not implemented")
}
func (UnimplementedGraphEngineServer) mustEmbedUnimplementedGraphEngineServer() {}
func (UnimplementedGraphEngineServer) testEmbeddedByValue()                     {}

// UnsafeGraphEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphEngineServer will
// result in compilation errors.
type UnsafeGraphEngineServer interface {
	mustEmbedUnimplementedGraphEngineServer()
}

func RegisterGraphEngineServer(s grpc.ServiceRegistrar, srv GraphEngineServer) {
	// If the following call panics, it indicates UnimplementedGraphEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphEngine_ServiceDesc, srv)
}

func _GraphEngine_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphEngineServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphEngine_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphEngineServer).GetSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphEngine_ApplyDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphDelta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphEngineServer).ApplyDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphEngine_ApplyDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphEngineServer).ApplyDelta(ctx, req.(*GraphDelta))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphEngine_QueryGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphEngineServer).QueryGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphEngine_QueryGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphEngineServer).QueryGraph(ctx, req.(*GraphQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphEngine_ServiceDesc is the grpc.ServiceDesc for GraphEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.graph.GraphEngine",
	HandlerType: (*GraphEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnapshot",
			Handler:    _GraphEngine_GetSnapshot_Handler,
		},
		{
			MethodName: "ApplyDelta",
			Handler:    _GraphEngine_ApplyDelta_Handler,
		},
		{
			MethodName: "QueryGraph",
			Handler:    _GraphEngine_QueryGraph_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/graph.proto",
}
