# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import graph_pb2 as proto_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSnapshot = channel.unary_unary(
                '/runtime.graph.GraphEngine/GetSnapshot',
                request_serializer=proto_dot_graph__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=proto_dot_graph__pb2.GraphSnapshot.FromString,
                _registered_method=True)
        self.ApplyDelta = channel.unary_unary(
                '/runtime.graph.GraphEngine/ApplyDelta',
                request_serializer=proto_dot_graph__pb2.GraphDelta.SerializeToString,
                response_deserializer=proto_dot_graph__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.QueryGraph = channel.unary_unary(
                '/runtime.graph.GraphEngine/QueryGraph',
                request_serializer=proto_dot_graph__pb2.GraphQuery.SerializeToString,
                response_deserializer=proto_dot_graph__pb2.GraphResponse.FromString,
                _registered_method=True)


class GraphEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyDelta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=proto_dot_graph__pb2.SnapshotRequest.FromString,
                    response_serializer=proto_dot_graph__pb2.GraphSnapshot.SerializeToString,
            ),
            'ApplyDelta': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyDelta,
                    request_deserializer=proto_dot_graph__pb2.GraphDelta.FromString,
                    response_serializer=proto_dot_graph__pb2.UpdateResponse.SerializeToString,
            ),
            'QueryGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryGraph,
                    request_deserializer=proto_dot_graph__pb2.GraphQuery.FromString,
                    response_serializer=proto_dot_graph__pb2.GraphResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.graph.GraphEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.graph.GraphEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.graph.GraphEngine/GetSnapshot',
            proto_dot_graph__pb2.SnapshotRequest.SerializeToString,
            proto_dot_graph__pb2.GraphSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyDelta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.graph.GraphEngine/ApplyDelta',
            proto_dot_graph__pb2.GraphDelta.SerializeToString,
            proto_dot_graph__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.graph.GraphEngine/QueryGraph',
            proto_dot_graph__pb2.GraphQuery.SerializeToString,
            proto_dot_graph__pb2.GraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
