# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/hypothesis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/hypothesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/hypothesis.proto\x12\x12runtime.hypothesis\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x03\n\x10\x41ttackHypothesis\x12\n\n\x02id\x18\x01 \x01(\t\x12\x35\n\tmechanism\x18\x02 \x01(\x0e\x32\".runtime.hypothesis.MechanismClass\x12\x15\n\rpath_node_ids\x18\x03 \x03(\t\x12\x12\n\nrisk_score\x18\x04 \x01(\x02\x12\x18\n\x10\x63onfidence_score\x18\x05 \x01(\x02\x12\x14\n\x0c\x65vidence_ids\x18\x06 \x03(\t\x12\x11\n\trationale\x18\x07 \x01(\t\x12\x1f\n\x17\x65xplainability_trace_id\x18\x08 \x01(\t\x12\x63\n\x18\x61rchitectural_indicators\x18\t \x03(\x0b\x32\x41.runtime.hypothesis.AttackHypothesis.ArchitecturalIndicatorsEntry\x12\x30\n\x0cgenerated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10priority_ranking\x18\x0b \x01(\x05\x1a>\n\x1c\x41rchitecturalIndicatorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8f\x01\n\x10HypothesisReport\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x38\n\nhypotheses\x18\x02 \x03(\x0b\x32$.runtime.hypothesis.AttackHypothesis\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\";\n\x10RegistryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0eregistered_ids\x18\x02 \x03(\t\"4\n\x0cSessionQuery\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08min_risk\x18\x02 \x01(\x02*\xb8\x01\n\x0eMechanismClass\x12\x15\n\x11UNKNOWN_MECHANISM\x10\x00\x12\x17\n\x13PARSER_DIFFERENTIAL\x10\x01\x12\x11\n\rIDENTITY_LEAK\x10\x02\x12\x17\n\x13WORKLOAD_ESCALATION\x10\x03\x12\x15\n\x11\x41SYNC_TRUST_DECAY\x10\x04\x12\x17\n\x13\x43ONSISTENCY_FAILURE\x10\x05\x12\x1a\n\x16STALE_AUTH_PROPAGATION\x10\x06\x32\xcd\x01\n\x12HypothesisRegistry\x12^\n\x10SubmitHypotheses\x12$.runtime.hypothesis.HypothesisReport\x1a$.runtime.hypothesis.RegistryResponse\x12W\n\rGetHypotheses\x12 .runtime.hypothesis.SessionQuery\x1a$.runtime.hypothesis.HypothesisReportB,Z*github.com/hacker/runtime/proto/hypothesisb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.hypothesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/hacker/runtime/proto/hypothesis'
  _globals['_ATTACKHYPOTHESIS_ARCHITECTURALINDICATORSENTRY']._loaded_options = None
  _globals['_ATTACKHYPOTHESIS_ARCHITECTURALINDICATORSENTRY']._serialized_options = b'8\001'
  _globals['_MECHANISMCLASS']._serialized_start=813
  _globals['_MECHANISMCLASS']._serialized_end=997
  _globals['_ATTACKHYPOTHESIS']._serialized_start=80
  _globals['_ATTACKHYPOTHESIS']._serialized_end=549
  _globals['_ATTACKHYPOTHESIS_ARCHITECTURALINDICATORSENTRY']._serialized_start=487
  _globals['_ATTACKHYPOTHESIS_ARCHITECTURALINDICATORSENTRY']._serialized_end=549
  _globals['_HYPOTHESISREPORT']._serialized_start=552
  _globals['_HYPOTHESISREPORT']._serialized_end=695
  _globals['_REGISTRYRESPONSE']._serialized_start=697
  _globals['_REGISTRYRESPONSE']._serialized_end=756
  _globals['_SESSIONQUERY']._serialized_start=758
  _globals['_SESSIONQUERY']._serialized_end=810
  _globals['_HYPOTHESISREGISTRY']._serialized_start=1000
  _globals['_HYPOTHESISREGISTRY']._serialized_end=1205
# @@protoc_insertion_point(module_scope)
