# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hypothesis_pb2 as proto_dot_hypothesis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/hypothesis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HypothesisRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitHypotheses = channel.unary_unary(
                '/runtime.hypothesis.HypothesisRegistry/SubmitHypotheses',
                request_serializer=proto_dot_hypothesis__pb2.HypothesisReport.SerializeToString,
                response_deserializer=proto_dot_hypothesis__pb2.RegistryResponse.FromString,
                _registered_method=True)
        self.GetHypotheses = channel.unary_unary(
                '/runtime.hypothesis.HypothesisRegistry/GetHypotheses',
                request_serializer=proto_dot_hypothesis__pb2.SessionQuery.SerializeToString,
                response_deserializer=proto_dot_hypothesis__pb2.HypothesisReport.FromString,
                _registered_method=True)


class HypothesisRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitHypotheses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHypotheses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HypothesisRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitHypotheses': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitHypotheses,
                    request_deserializer=proto_dot_hypothesis__pb2.HypothesisReport.FromString,
                    response_serializer=proto_dot_hypothesis__pb2.RegistryResponse.SerializeToString,
            ),
            'GetHypotheses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHypotheses,
                    request_deserializer=proto_dot_hypothesis__pb2.SessionQuery.FromString,
                    response_serializer=proto_dot_hypothesis__pb2.HypothesisReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.hypothesis.HypothesisRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.hypothesis.HypothesisRegistry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HypothesisRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitHypotheses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.hypothesis.HypothesisRegistry/SubmitHypotheses',
            proto_dot_hypothesis__pb2.HypothesisReport.SerializeToString,
            proto_dot_hypothesis__pb2.RegistryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHypotheses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.hypothesis.HypothesisRegistry/GetHypotheses',
            proto_dot_hypothesis__pb2.SessionQuery.SerializeToString,
            proto_dot_hypothesis__pb2.HypothesisReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
