# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/orchestration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/orchestration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/orchestration.proto\x12\x15runtime.orchestration\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\rReplaySession\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x16\n\x0estart_sequence\x18\x02 \x01(\x03\x12\x14\n\x0c\x65nd_sequence\x18\x03 \x01(\x03\x12\x14\n\x0creplay_speed\x18\x04 \x01(\x02\"b\n\x0eIngestionEvent\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06source\x18\x03 \x01(\t\"<\n\x10GraphUpdateEvent\x12\x10\n\x08\x64\x65lta_id\x18\x01 \x01(\t\x12\x16\n\x0enodes_affected\x18\x02 \x01(\x05\"\x8a\x01\n\rRuntimeStatus\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x34\n\x05state\x18\x02 \x01(\x0e\x32%.runtime.orchestration.LifecycleState\x12\x13\n\x0b\x65vent_count\x18\x03 \x01(\x03\x12\x1a\n\x12\x63onfidence_average\x18\x04 \x01(\x02\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"\xb6\x01\n\rSessionConfig\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12W\n\x12\x65nvironment_params\x18\x02 \x03(\x0b\x32;.runtime.orchestration.SessionConfig.EnvironmentParamsEntry\x1a\x38\n\x16\x45nvironmentParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*]\n\x0eLifecycleState\x12\x10\n\x0cINITIALIZING\x10\x00\x12\r\n\tSTREAMING\x10\x01\x12\x0e\n\nCONVERGING\x10\x02\x12\x0f\n\x0bHIBERNATING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x32\x84\x03\n\x11OrchestrationCore\x12Z\n\x0cStartSession\x12$.runtime.orchestration.SessionConfig\x1a$.runtime.orchestration.RuntimeStatus\x12Z\n\x0bStopSession\x12%.runtime.orchestration.SessionRequest\x1a$.runtime.orchestration.RuntimeStatus\x12X\n\tGetStatus\x12%.runtime.orchestration.SessionRequest\x1a$.runtime.orchestration.RuntimeStatus\x12]\n\rTriggerReplay\x12$.runtime.orchestration.ReplaySession\x1a$.runtime.orchestration.RuntimeStatus0\x01\x42/Z-github.com/hacker/runtime/proto/orchestrationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.orchestration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/hacker/runtime/proto/orchestration'
  _globals['_SESSIONCONFIG_ENVIRONMENTPARAMSENTRY']._loaded_options = None
  _globals['_SESSIONCONFIG_ENVIRONMENTPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_LIFECYCLESTATE']._serialized_start=716
  _globals['_LIFECYCLESTATE']._serialized_end=809
  _globals['_REPLAYSESSION']._serialized_start=85
  _globals['_REPLAYSESSION']._serialized_end=188
  _globals['_INGESTIONEVENT']._serialized_start=190
  _globals['_INGESTIONEVENT']._serialized_end=288
  _globals['_GRAPHUPDATEEVENT']._serialized_start=290
  _globals['_GRAPHUPDATEEVENT']._serialized_end=350
  _globals['_RUNTIMESTATUS']._serialized_start=353
  _globals['_RUNTIMESTATUS']._serialized_end=491
  _globals['_SESSIONREQUEST']._serialized_start=493
  _globals['_SESSIONREQUEST']._serialized_end=529
  _globals['_SESSIONCONFIG']._serialized_start=532
  _globals['_SESSIONCONFIG']._serialized_end=714
  _globals['_SESSIONCONFIG_ENVIRONMENTPARAMSENTRY']._serialized_start=658
  _globals['_SESSIONCONFIG_ENVIRONMENTPARAMSENTRY']._serialized_end=714
  _globals['_ORCHESTRATIONCORE']._serialized_start=812
  _globals['_ORCHESTRATIONCORE']._serialized_end=1200
# @@protoc_insertion_point(module_scope)
