# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/reasoning.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/reasoning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import graph_pb2 as proto_dot_graph__pb2
from . import hypothesis_pb2 as proto_dot_hypothesis__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/reasoning.proto\x12\x11runtime.reasoning\x1a\x11proto/graph.proto\x1a\x16proto/hypothesis.proto\"\xde\x01\n\rInferenceTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12/\n\tsub_graph\x18\x03 \x01(\x0b\x32\x1c.runtime.graph.GraphSnapshot\x12\x44\n\nparameters\x18\x04 \x03(\x0b\x32\x30.runtime.reasoning.InferenceTask.ParametersEntry\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xba\x01\n\x0fInferenceResult\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x38\n\nhypotheses\x18\x02 \x03(\x0b\x32$.runtime.hypothesis.AttackHypothesis\x12\x43\n\x12\x63onfidence_updates\x18\x03 \x03(\x0b\x32\'.runtime.reasoning.ConfidenceRefinement\x12\x17\n\x0freasoning_trace\x18\x04 \x01(\t\"P\n\x14\x43onfidenceRefinement\x12\x11\n\ttarget_id\x18\x01 \x01(\t\x12\x12\n\nadjustment\x18\x02 \x01(\x02\x12\x11\n\trationale\x18\x03 \x01(\t\"N\n\x1b\x43onfidenceRefinementRequest\x12\x11\n\tentity_id\x18\x01 \x01(\t\x12\x1c\n\x14related_evidence_ids\x18\x02 \x03(\t2\xb5\x01\n\x0fReasoningWorker\x12M\n\x05Infer\x12 .runtime.reasoning.InferenceTask\x1a\".runtime.reasoning.InferenceResult\x12S\n\x0f\x41nalyzeTopology\x12\x1c.runtime.graph.GraphSnapshot\x1a\".runtime.reasoning.InferenceResult2p\n\x10\x43onfidenceEngine\x12\\\n\x06Refine\x12..runtime.reasoning.ConfidenceRefinementRequest\x1a\".runtime.reasoning.InferenceResultB+Z)github.com/hacker/runtime/proto/reasoningb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.reasoning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/hacker/runtime/proto/reasoning'
  _globals['_INFERENCETASK_PARAMETERSENTRY']._loaded_options = None
  _globals['_INFERENCETASK_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_INFERENCETASK']._serialized_start=88
  _globals['_INFERENCETASK']._serialized_end=310
  _globals['_INFERENCETASK_PARAMETERSENTRY']._serialized_start=261
  _globals['_INFERENCETASK_PARAMETERSENTRY']._serialized_end=310
  _globals['_INFERENCERESULT']._serialized_start=313
  _globals['_INFERENCERESULT']._serialized_end=499
  _globals['_CONFIDENCEREFINEMENT']._serialized_start=501
  _globals['_CONFIDENCEREFINEMENT']._serialized_end=581
  _globals['_CONFIDENCEREFINEMENTREQUEST']._serialized_start=583
  _globals['_CONFIDENCEREFINEMENTREQUEST']._serialized_end=661
  _globals['_REASONINGWORKER']._serialized_start=664
  _globals['_REASONINGWORKER']._serialized_end=845
  _globals['_CONFIDENCEENGINE']._serialized_start=847
  _globals['_CONFIDENCEENGINE']._serialized_end=959
# @@protoc_insertion_point(module_scope)
