# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import graph_pb2 as proto_dot_graph__pb2
from . import reasoning_pb2 as proto_dot_reasoning__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/reasoning_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReasoningWorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Infer = channel.unary_unary(
                '/runtime.reasoning.ReasoningWorker/Infer',
                request_serializer=proto_dot_reasoning__pb2.InferenceTask.SerializeToString,
                response_deserializer=proto_dot_reasoning__pb2.InferenceResult.FromString,
                _registered_method=True)
        self.AnalyzeTopology = channel.unary_unary(
                '/runtime.reasoning.ReasoningWorker/AnalyzeTopology',
                request_serializer=proto_dot_graph__pb2.GraphSnapshot.SerializeToString,
                response_deserializer=proto_dot_reasoning__pb2.InferenceResult.FromString,
                _registered_method=True)


class ReasoningWorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Infer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTopology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReasoningWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Infer': grpc.unary_unary_rpc_method_handler(
                    servicer.Infer,
                    request_deserializer=proto_dot_reasoning__pb2.InferenceTask.FromString,
                    response_serializer=proto_dot_reasoning__pb2.InferenceResult.SerializeToString,
            ),
            'AnalyzeTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTopology,
                    request_deserializer=proto_dot_graph__pb2.GraphSnapshot.FromString,
                    response_serializer=proto_dot_reasoning__pb2.InferenceResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.reasoning.ReasoningWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.reasoning.ReasoningWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReasoningWorker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Infer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.reasoning.ReasoningWorker/Infer',
            proto_dot_reasoning__pb2.InferenceTask.SerializeToString,
            proto_dot_reasoning__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.reasoning.ReasoningWorker/AnalyzeTopology',
            proto_dot_graph__pb2.GraphSnapshot.SerializeToString,
            proto_dot_reasoning__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ConfidenceEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Refine = channel.unary_unary(
                '/runtime.reasoning.ConfidenceEngine/Refine',
                request_serializer=proto_dot_reasoning__pb2.ConfidenceRefinementRequest.SerializeToString,
                response_deserializer=proto_dot_reasoning__pb2.InferenceResult.FromString,
                _registered_method=True)


class ConfidenceEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Refine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfidenceEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Refine': grpc.unary_unary_rpc_method_handler(
                    servicer.Refine,
                    request_deserializer=proto_dot_reasoning__pb2.ConfidenceRefinementRequest.FromString,
                    response_serializer=proto_dot_reasoning__pb2.InferenceResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.reasoning.ConfidenceEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.reasoning.ConfidenceEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfidenceEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Refine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.reasoning.ConfidenceEngine/Refine',
            proto_dot_reasoning__pb2.ConfidenceRefinementRequest.SerializeToString,
            proto_dot_reasoning__pb2.InferenceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
