# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/signal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/signal.proto\x12\x0eruntime.signal\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x02\n\x13\x41rchitecturalSignal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10\x61sset_identifier\x18\x04 \x01(\t\x12G\n\nattributes\x18\x05 \x03(\x0b\x32\x33.runtime.signal.ArchitecturalSignal.AttributesEntry\x12\x17\n\x0finferred_traits\x18\x06 \x03(\t\x12\x12\n\nconfidence\x18\x07 \x01(\x02\x12\x30\n\x08metadata\x18\x08 \x01(\x0b\x32\x1e.runtime.signal.SignalMetadata\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf6\x01\n\x0eSignalMetadata\x12\x1a\n\x12reasoning_trace_id\x18\x01 \x01(\t\x12\x15\n\rprovenance_id\x18\x02 \x01(\t\x12\x14\n\x0ctool_version\x18\x03 \x01(\t\x12\x17\n\x0fscan_session_id\x18\x04 \x01(\t\x12K\n\x0f\x63orrelation_ids\x18\x05 \x03(\x0b\x32\x32.runtime.signal.SignalMetadata.CorrelationIdsEntry\x1a\x35\n\x13\x43orrelationIdsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"N\n\x11IngestionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x11\n\tsignal_id\x18\x03 \x01(\t2\xbd\x01\n\x0fSignalIngestion\x12P\n\x06Ingest\x12#.runtime.signal.ArchitecturalSignal\x1a!.runtime.signal.IngestionResponse\x12X\n\x0cStreamIngest\x12#.runtime.signal.ArchitecturalSignal\x1a!.runtime.signal.IngestionResponse(\x01\x42(Z&github.com/hacker/runtime/proto/signalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/hacker/runtime/proto/signal'
  _globals['_ARCHITECTURALSIGNAL_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_ARCHITECTURALSIGNAL_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_SIGNALMETADATA_CORRELATIONIDSENTRY']._loaded_options = None
  _globals['_SIGNALMETADATA_CORRELATIONIDSENTRY']._serialized_options = b'8\001'
  _globals['_ARCHITECTURALSIGNAL']._serialized_start=72
  _globals['_ARCHITECTURALSIGNAL']._serialized_end=413
  _globals['_ARCHITECTURALSIGNAL_ATTRIBUTESENTRY']._serialized_start=364
  _globals['_ARCHITECTURALSIGNAL_ATTRIBUTESENTRY']._serialized_end=413
  _globals['_SIGNALMETADATA']._serialized_start=416
  _globals['_SIGNALMETADATA']._serialized_end=662
  _globals['_SIGNALMETADATA_CORRELATIONIDSENTRY']._serialized_start=609
  _globals['_SIGNALMETADATA_CORRELATIONIDSENTRY']._serialized_end=662
  _globals['_INGESTIONRESPONSE']._serialized_start=664
  _globals['_INGESTIONRESPONSE']._serialized_end=742
  _globals['_SIGNALINGESTION']._serialized_start=745
  _globals['_SIGNALINGESTION']._serialized_end=934
# @@protoc_insertion_point(module_scope)
